version: '3.6'

services:
  web:
    build:
      context: .
    container_name: rourawp
    network_mode: bridge
    env_file:
      - ./docker/var.env
    environment:
      - VIRTUAL_HOST=rourawp.docker
    volumes:
      - ./code/wp-content/themes:/var/www/html/wp-content/themes
      - ./docker/wp-content/uploads:/var/www/html/wp-content/uploads
      - ./docker/wp-content/plugins:/var/www/html/wp-content/plugins
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:5
    container_name: rourawp-db
    network_mode: bridge
    env_file:
      - ./docker/var.env
    volumes:
      - ./docker/mysql:/var/lib/mysql
